spring:
  application:
    name: stock-service

server:
  port: 8301

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    instance:
      hostname: localhost


